name: ipapico_flutter
description: Get IP address, geolocation and other metadata info from https://ipapi.co/
version: 0.0.3
maintainer: Miguel Vega (@atleugim)

homepage: https://github.com/atleugim/ipapico-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.6
  build_runner: ^2.1.10
