name: ipapico_flutter
description: Get ip and timezone and other metadata info
version: 0.0.1
homepage: https://github.com/atleugim/ipapico-flutter

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.0.3
  dio: ^4.0.6
  equatable: ^2.0.3
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  json_serializable: ^6.1.6
  build_runner: ^2.1.10

flutter:
